### ISSUE TITLE
Float.to_string/2 is deprecated

### ISSUE THREAD

**Issue by wli0503** [akira/exq#238]
Elixir Version: 1.4.2
Exq Version: 0.7.3

Try to open `iex -S mix` on the setup resulting in:
```
warning: Float.to_string/2 is deprecated, use :erlang.float_to_binary/2 instead
  (elixir) lib/float.ex:414: Float.to_string/2
  (exq) lib/exq/redis/job_queue.ex:131: Exq.Redis.JobQueue.scheduler_dequeue/2
  (exq) lib/exq/scheduler/server.ex:68: Exq.Scheduler.Server.dequeue/1
  (exq) lib/exq/scheduler/server.ex:56: Exq.Scheduler.Server.handle_info/2
  (stdlib) gen_server.erl:601: :gen_server.try_dispatch/4
```
It's popping up every second and prevent normal use of the console interface. It's part of the issue with the new `elixir` upgrade.

**Comment by wli0503** [comment]
Nvm. I've updated the `mix.exs` into `exq: 0.8.3` and the problem is solved. Thanks!
