### ISSUE TITLE
no function clause matching in Exq.Manager.Server.handle_call/3

### ISSUE THREAD

**Issue by rafaltrojanowski** [akira/exq#451]
Calling `Exq.Api.queues(Domain.Exq)` throws an exception. Here is a stacktrace:

```
[error] GenServer Domain.Exq terminating
** (FunctionClauseError) no function clause matching in Exq.Manager.Server.handle_call/3
    (exq 0.15.0) lib/exq/manager/server.ex:178: Exq.Manager.Server.handle_call(:queues, {#PID<0.3047.0>, [:alias | #Reference<0.165069303.2688352261.108478>]}, %Exq.Manager.Server.State{dequeuers: %{"default" => {Exq.Dequeue.Local, %Exq.Dequeue.Local.State{current: 0, max: 100}}, "scraper" => {Exq.Dequeue.Local, %Exq.Dequeue.Local.State{current: 0, max: 100}}}, enqueuer: Domain.Exq.Enqueuer, metadata: Domain.Exq.Worker.Metadata, middleware: Domain.Exq.Middleware.Server, namespace: "exq", node_id: "Rafas-MacBook-Pro", pid: #PID<0.3068.0>, poll_timeout: 100, queues: ["default", "scraper"], redis: Domain.Exq.Redis.Client, scheduler_poll_timeout: 200, stats: Domain.Exq.Stats, workers_sup: Domain.Exq.Worker.Sup})
    (stdlib 3.15) gen_server.erl:721: :gen_server.try_handle_call/4
    (stdlib 3.15) gen_server.erl:750: :gen_server.handle_msg/6
    (stdlib 3.15) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Last message (from #PID<0.3047.0>): :queues
State: %Exq.Manager.Server.State{dequeuers: %{"default" => {Exq.Dequeue.Local, %Exq.Dequeue.Local.State{current: 0, max: 100}}, "scraper" => {Exq.Dequeue.Local, %Exq.Dequeue.Local.State{current: 0, max: 100}}}, enqueuer: Domain.Exq.Enqueuer, metadata: Domain.Exq.Worker.Metadata, middleware: Domain.Exq.Middleware.Server, namespace: "exq", node_id: "Rafas-MacBook-Pro", pid: #PID<0.3068.0>, poll_timeout: 100, queues: ["default", "scraper"], redis: Domain.Exq.Redis.Client, scheduler_poll_timeout: 200, stats: Domain.Exq.Stats, workers_sup: Domain.Exq.Worker.Sup}
Client #PID<0.3047.0> is alive

    (stdlib 3.15) gen.erl:233: :gen.do_call/4
    (elixir 1.12.2) lib/gen_server.ex:1021: GenServer.call/3
    (stdlib 3.15) erl_eval.erl:685: :erl_eval.do_apply/6
    (elixir 1.12.2) src/elixir.erl:280: :elixir.recur_eval/3
    (elixir 1.12.2) src/elixir.erl:265: :elixir.eval_forms/3
    (iex 1.12.2) lib/iex/evaluator.ex:298: IEx.Evaluator.handle_eval/3
    (iex 1.12.2) lib/iex/evaluator.ex:274: IEx.Evaluator.do_eval/3
    (iex 1.12.2) lib/iex/evaluator.ex:263: IEx.Evaluator.eval/3
    (iex 1.12.2) lib/iex/evaluator.ex:157: IEx.Evaluator.loop/1
    (iex 1.12.2) lib/iex/evaluator.ex:32: IEx.Evaluator.init/4
    (stdlib 3.15) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
** (exit) exited in: GenServer.call(Domain.Exq, :queues, 5000)
    ** (EXIT) an exception was raised:
        ** (FunctionClauseError) no function clause matching in Exq.Manager.Server.handle_call/3
            (exq 0.15.0) lib/exq/manager/server.ex:178: Exq.Manager.Server.handle_call(:queues, {#PID<0.3047.0>, [:alias | #Reference<0.165069303.2688352261.108478>]}, %Exq.Manager.Server.State{dequeuers: %{"default" => {Exq.Dequeue.Local, %Exq.Dequeue.Local.State{current: 0, max: 100}}, "scraper" => {Exq.Dequeue.Local, %Exq.Dequeue.Local.State{current: 0, max: 100}}}, enqueuer: Domain.Exq.Enqueuer, metadata: Domain.Exq.Worker.Metadata, middleware: Domain.Exq.Middleware.Server, namespace: "exq", node_id: "Rafas-MacBook-Pro", pid: #PID<0.3068.0>, poll_timeout: 100, queues: ["default", "scraper"], redis: Domain.Exq.Redis.Client, scheduler_poll_timeout: 200, stats: Domain.Exq.Stats, workers_sup: Domain.Exq.Worker.Sup})
            (stdlib 3.15) gen_server.erl:721: :gen_server.try_handle_call/4
            (stdlib 3.15) gen_server.erl:750: :gen_server.handle_msg/6
            (stdlib 3.15) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
    (elixir 1.12.2) lib/gen_server.ex:1024: GenServer.call/3
```

How can I use `Exq.Api` in an app or IEx session?

**Comment by ananthakumaran** [comment]
could you try `Exq.Api.queues(Domain.Exq.Api)` or `Exq.Api.queues(Exq.Api)` if you have not customized the name

**Comment by rafaltrojanowski** [comment]
@ananthakumaran Thanks for the quick reply, it works.
