### ISSUE TITLE
expected :timeout to be an integer of :infinity

### ISSUE THREAD

**Issue by kitplummer** [akira/exq#480]
Out-the-box getting this error.  Can't seen to get around it.  Anyone else see it?

```
** (Mix) Could not start application exq: Exq.start(:normal, []) returned an error: shutdown: failed to start child: Exq.Manager.Server
    ** (EXIT) an exception was raised:
        ** (RuntimeError) 


====================================================================================================
ERROR! Could not connect to Redis!

Configuration passed in: [[host: "127.0.0.1", port: 6379, database: 0, password: nil, name: Exq.Redis.Client, socket_opts: []]]
Error: :error
Reason: %ArgumentError{message: "expected :timeout to be an integer of :infinity, got: nil"}

Make sure Redis is running, and your configuration matches Redis settings.
====================================================================================================

            (exq 0.16.2) lib/exq/manager/server.ex:437: Exq.Manager.Server.check_redis_connection/1
            (exq 0.16.2) lib/exq/manager/server.ex:179: Exq.Manager.Server.init/1
            (stdlib 4.1.1) gen_server.erl:851: :gen_server.init_it/2
            (stdlib 4.1.1) gen_server.erl:814: :gen_server.init_it/6
            (stdlib 4.1.1) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
```

Probably me being dumb.  But copied the config straight into a freshy new mix project.

**Comment by ananthakumaran** [comment]
Could you upgrade to 0.17.0, this issue has been fixed. I will update the
readme soon, just realised it is still pointing to last release.

**Comment by kitplummer** [comment]
Doh, yep - that's it.  Sorry.
