### ISSUE TITLE
Missing assign `:worker_module`

### ISSUE THREAD

**Issue by dmuhs** [akira/exq#486]
I have a simple worker setup, almost identical to the samples in the readme file, only with the names changed. When I run it with any middleware enabled (e.g. only `[Exq.Middleware.Unique]`), all jobs fail with the following error:

```elixir

21:56:27.015 [error] GenServer #PID<0.287.0> terminating
** (KeyError) key :worker_module not found in: %{
  host: "airbucket",
  queue: "default",
  stats: Exq.Stats,
  namespace: "exq",
  manager: #PID<0.227.0>,
  redis: Exq.Redis.Client,
  job_serialized: "{\"args\":[\"dmuhs.blog\"],\"queue\":\"default\",\"retry\":0,\"enqueued_at\":1695153386.944662,\"jid\":\"92bc95cd-624a-4e51-b7f6-3e1d2f90d627\",\"class\":\"Mojo.Extract.CrtSh\"}"
}
    (exq 0.19.0) lib/exq/worker/server.ex:110: Exq.Worker.Server.handle_cast/2
    (stdlib 5.0.2) gen_server.erl:1103: :gen_server.try_handle_cast/3
    (stdlib 5.0.2) gen_server.erl:1165: :gen_server.handle_msg/6
    (stdlib 5.0.2) proc_lib.erl:241: :proc_lib.init_p_do_apply/3
Last message: {:"$gen_cast", :dispatch}
State: %Exq.Worker.Server.State{job_serialized: "{\"args\":[\"dmuhs.blog\"],\"queue\":\"default\",\"retry\":0,\"enqueued_at\":1695153386.944662,\"jid\":\"92bc95cd-624a-4e51-b7f6-3e1d2f90d627\",\"class\":\"Mojo.Extract.CrtSh\"}", manager: #PID<0.227.0>, queue: "default", namespace: "exq", stats: Exq.Stats, host: "airbucket", redis: Exq.Redis.Client, middleware: Exq.Middleware.Server, pipeline: %Exq.Middleware.Pipeline{assigns: %{host: "airbucket", queue: "default", stats: Exq.Stats, namespace: "exq", manager: #PID<0.227.0>, redis: Exq.Redis.Client, job_serialized: "{\"args\":[\"dmuhs.blog\"],\"queue\":\"default\",\"retry\":0,\"enqueued_at\":1695153386.944662,\"jid\":\"92bc95cd-624a-4e51-b7f6-3e1d2f90d627\",\"class\":\"Mojo.Extract.CrtSh\"}"}, halted: false, terminated: false, worker_pid: #PID<0.287.0>, event: :before_work}, metadata: Exq.Worker.Metadata, middleware_state: []}
```

This is my exq config:

```elixir
config :exq,
  name: Exq,
  host: "127.0.0.1",
  port: 6379,
  password: "changeme",
  namespace: "exq",
  concurrency: 1000,
  queues: ["default"],
  poll_timeout: 50,
  scheduler_poll_timeout: 200,
  scheduler_enable: true,
  max_retries: 0,
  mode: :default,
  shutdown_timeout: 5000,
  middleware: [Exq.Middleware.Unique]
```

A similar error occurs e.g. with only `Exq.Middleware.Logger` enabled:

```elixir
22:14:07.814 [error] GenServer #PID<0.246.0> terminating
** (KeyError) key :worker_module not found in: %{
  host: "airbucket",
  queue: "default",
  stats: Exq.Stats,
  namespace: "exq",
  manager: #PID<0.227.0>,
  redis: Exq.Redis.Client,
  job_serialized: "{\"args\":[\"dmuhs.blog\"],\"queue\":\"default\",\"retry\":0,\"enqueued_at\":1695153386.944662,\"jid\":\"92bc95cd-624a-4e51-b7f6-3e1d2f90d627\",\"class\":\"Mojo.Extract.CrtSh\"}"
}
    (exq 0.19.0) lib/exq/middleware/logger.ex:31: Exq.Middleware.Logger.log_context/1
    (exq 0.19.0) lib/exq/middleware/logger.ex:9: Exq.Middleware.Logger.before_work/1
    (exq 0.19.0) lib/exq/middleware/pipeline.ex:86: Exq.Middleware.Pipeline.chain/2
    (exq 0.19.0) lib/exq/worker/server.ex:96: Exq.Worker.Server.handle_cast/2
    (stdlib 5.0.2) gen_server.erl:1103: :gen_server.try_handle_cast/3
    (stdlib 5.0.2) gen_server.erl:1165: :gen_server.handle_msg/6
    (stdlib 5.0.2) proc_lib.erl:241: :proc_lib.init_p_do_apply/3
Last message: {:"$gen_cast", :work}
State: %Exq.Worker.Server.State{job_serialized: "{\"args\":[\"dmuhs.blog\"],\"queue\":\"default\",\"retry\":0,\"enqueued_at\":1695153386.944662,\"jid\":\"92bc95cd-624a-4e51-b7f6-3e1d2f90d627\",\"class\":\"Mojo.Extract.CrtSh\"}", manager: #PID<0.227.0>, queue: "default", namespace: "exq", stats: Exq.Stats, host: "airbucket", redis: Exq.Redis.Client, middleware: Exq.Middleware.Server, pipeline: nil, metadata: Exq.Worker.Metadata, middleware_state: nil}
```

As soon as the middleware key is commented out, the worker works fine, indicating that it's an issue rooted deeper in `exq`. I'm running on the latest Erlang/Elixir branches but ran into the same error with the latest stable versions.

```
elixir                       git@github.com:asdf-vm/asdf-elixir.git master d08f506
erlang                       git@github.com:asdf-vm/asdf-erlang.git master 0463971
```

**Comment by ananthakumaran** [comment]
Exq internally uses the middleware as well and some of them (Job, Manager) are mandatory. So what's happening here is that when you don't override the middleware config, Exq will use the default. But once you override it, the required middleware would be missing and that would break the system. Start with the default middleware config and try to add/remove. You can't remove the Job and Manager middleware though

https://github.com/akira/exq/blob/ee4eb16028bc3626daed9d3680920503ea9c37e7/lib/exq/support/config.ex#L33-L39

**Comment by dmuhs** [comment]
@ananthakumaran Thanks, that clears things up!
